In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as st
import datetime
import calendar

In [29]:
# Load up excel data files 

coal_df = pd.read_excel('Resources/coal.xlsx')
natural_gas_df = pd.read_excel('Resources/Natural_Gas.xlsx')
petroleum_df = pd.read_excel('Resources/Petroleum.xlsx')
renewables_df = pd.read_excel('Resources/Renewable_Energy.xlsx')

In [20]:
# Clean out Coal data
clean_coal = coal_df.drop(["Waste Coal Supplied (Thousand Short Tons)","Coal Imports (Thousand Short Tons)","Coal Exports (Thousand Short Tons)","Coal Losses and Unaccounted for (Thousand Short Tons)"],axis=1)
clean_coal

,Month,Coal Production (Thousand Short Tons),Coal Net Imports (Thousand Short Tons),Coal Stock Change (Thousand Short Tons),Coal Consumption (Thousand Short Tons)
0,1973-01-01,49901.000,-2993,7744.46,50578.6
1,1973-02-01,46461.000,-2672,-1997.88,45564.8
2,1973-03-01,51188.000,-3467,1189.42,45403
3,1973-04-01,47580.000,-5117,1218.52,43326.5
4,1973-05-01,52061.000,-5221,4230.62,43999.8
...,...,...,...,...,...
568,2020-05-01,36934.071,-4221.94,2648.24,29787.3
569,2020-06-01,39258.833,-4295.05,-5671.24,39902.4
570,2020-07-01,43086.574,-4885.63,-13484.3,53263.5
571,2020-08-01,47393.655,-4208.67,Not Available,Not Available
572,2020-09-01,45093.714,Not Available,Not Available,Not Available

In [24]:
# Clean out Natural gas data
clean_natural_gas = natural_gas_df.drop(["Natural Gas Gross Withdrawals (Billion Cubic Feet)","NGPL Production (Billion Cubic Feet)","Natural Gas Production (Dry) (Billion Cubic Feet)","Natural Gas Net Imports (Billion Cubic Feet)", "Supplemental Gaseous Fuels (Billion Cubic Feet)","Natural Gas Balancing Item (Billion Cubic Feet)" ],axis=1)
clean_natural_gas

,Month,Natural Gas Marketed Production (Wet) (Billion Cubic Feet),Natural Gas Imports (Billion Cubic Feet),Natural Gas Exports (Billion Cubic Feet),Natural Gas Net Storage Withdrawals (Billion Cubic Feet),Natural Gas Consumption (Billion Cubic Feet)
0,1973-01-01,1948.000,92.694,5.808,Not Available,2348.000
1,1973-02-01,1962.000,83.870,6.079,Not Available,2126.000
2,1973-03-01,1907.000,91.581,4.021,Not Available,2015.000
3,1973-04-01,1814.000,88.407,8.017,Not Available,1835.000
4,1973-05-01,1898.000,85.844,8.741,Not Available,1729.000
...,...,...,...,...,...,...
566,2020-03-01,3156.571,217.087,497.399,49.134,2709.209
567,2020-04-01,2992.824,193.401,420.731,-306.21,2243.949
568,2020-05-01,2925.016,189.403,395.307,-448.006,2068.441
569,2020-06-01,2872.114,185.143,338.444,-357.949,2135.630
570,2020-07-01,3021.945,212.953,335.373,-161.372,2494.742

In [25]:
# Clean out Petroleum data
clean_petroleum = petroleum_df.drop (["Crude Oil Production, 48 States (Thousand Barrels per Day)","Crude Oil Production, Alaska (Thousand Barrels per Day)","Crude Oil Production, Total (Thousand Barrels per Day)","Natural Gas Liquids Production (Thousand Barrels per Day)","Renewable Fuels and Oxygenate Plant Net Production (Thousand Barrels per Day)","Petroleum Processing Gain (Thousand Barrels per Day)","Petroleum Net Imports (Thousand Barrels per Day)","Petroleum Adjustments (Thousand Barrels per Day)"],axis=1)
clean_petroleum

,Month,Total Petroleum Field Production (Thousand Barrels per Day),Petroleum Imports (Thousand Barrels per Day),Petroleum Exports (Thousand Barrels per Day),Petroleum Stock Change (Thousand Barrels per Day),Petroleum Products Supplied (Thousand Barrels per Day)
0,1973-01-01,10855.968,5857.097,210.613,-1718.323,18712.645
1,1973-02-01,11140.107,6507.286,260.964,-1407.357,19094.143
2,1973-03-01,11006.419,6610.161,224.194,672.806,17216.226
3,1973-04-01,11041.500,5593.367,275.567,871.267,15920.533
4,1973-05-01,11001.645,5840.935,237.387,658.032,16625.806
...,...,...,...,...,...,...
568,2020-05-01,14763.656,7756.871,6817.574,1242.020,16103.228
569,2020-06-01,15643.708,8367.233,7692.178,1168.138,17435.204
570,2020-07-01,16352.690,7845.581,8411.704,-56.598,18322.588
571,2020-08-01,15209.705,7404.555,7799.194,-1070.773,18297.591
572,2020-09-01,15934.000,7303.737,7818.367,-424.440,17883.111

In [27]:
# Clean out renewable data - kept all data
clean_renewables = renewables_df
clean_renewables

,Month,Wood Energy Production (Trillion Btu),Biofuels Production (Trillion Btu),Total Biomass Energy Production (Trillion Btu),Total Renewable Energy Production (Trillion Btu),Hydroelectric Power Consumption (Trillion Btu),Geothermal Energy Consumption (Trillion Btu),Solar Energy Consumption (Trillion Btu),Wind Energy Consumption (Trillion Btu),Wood Energy Consumption (Trillion Btu),Waste Energy Consumption (Trillion Btu),Biofuels Consumption (Trillion Btu),Total Biomass Energy Consumption (Trillion Btu),Total Renewable Energy Consumption (Trillion Btu)
0,1973-01-01,129.630,Not Available,129.787,403.981,272.703,1.491,Not Available,Not Available,129.630,0.157,Not Available,129.787,403.981
1,1973-02-01,117.194,Not Available,117.338,360.900,242.199,1.363,Not Available,Not Available,117.194,0.144,Not Available,117.338,360.900
2,1973-03-01,129.763,Not Available,129.938,400.161,268.810,1.412,Not Available,Not Available,129.763,0.176,Not Available,129.938,400.161
3,1973-04-01,125.462,Not Available,125.636,380.470,253.185,1.649,Not Available,Not Available,125.462,0.174,Not Available,125.636,380.470
4,1973-05-01,129.624,Not Available,129.834,392.141,260.770,1.537,Not Available,Not Available,129.624,0.210,Not Available,129.834,392.141
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,2020-03-01,189.162,183.663,410.886,995.023,202.739,18.946,94.035,268.416,179.141,38.061,162.492,379.693,963.830
567,2020-04-01,182.014,112.893,330.230,919.439,189.099,17.553,113.675,268.881,173.630,35.323,112.394,321.348,910.557
568,2020-05-01,190.617,136.585,363.013,1040.212,268.273,18.312,134.061,256.554,182.582,35.810,145.906,364.299,1041.498
569,2020-06-01,179.179,164.111,375.833,1060.066,260.567,17.424,131.784,274.458,169.606,32.542,166.727,368.875,1053.109
570,2020-07-01,185.801,180.789,401.080,1003.547,236.338,18.571,140.897,206.661,176.805,34.490,179.397,390.692,993.159

In [34]:
# Merging data - part 1
combined1_df = pd.merge(clean_coal,clean_renewables, on="Month")

In [35]:
# Merging data - part 2
combined2_df = pd.merge(clean_petroleum,clean_natural_gas, on="Month")

In [65]:
# Merging data - part 3
final_combine = pd.merge(combined1_df ,combined2_df, on="Month")
final_combine

,Month,Coal Production (Thousand Short Tons),Coal Net Imports (Thousand Short Tons),Coal Stock Change (Thousand Short Tons),Coal Consumption (Thousand Short Tons),Wood Energy Production (Trillion Btu),Biofuels Production (Trillion Btu),Total Biomass Energy Production (Trillion Btu),Total Renewable Energy Production (Trillion Btu),Hydroelectric Power Consumption (Trillion Btu),...,Total Petroleum Field Production (Thousand Barrels per Day),Petroleum Imports (Thousand Barrels per Day),Petroleum Exports (Thousand Barrels per Day),Petroleum Stock Change (Thousand Barrels per Day),Petroleum Products Supplied (Thousand Barrels per Day),Natural Gas Marketed Production (Wet) (Billion Cubic Feet),Natural Gas Imports (Billion Cubic Feet),Natural Gas Exports (Billion Cubic Feet),Natural Gas Net Storage Withdrawals (Billion Cubic Feet),Natural Gas Consumption (Billion Cubic Feet)
0,1973-01-01,49901.000,-2993,7744.46,50578.6,129.630,Not Available,129.787,403.981,272.703,...,10855.968,5857.097,210.613,-1718.323,18712.645,1948.000,92.694,5.808,Not Available,2348.000
1,1973-02-01,46461.000,-2672,-1997.88,45564.8,117.194,Not Available,117.338,360.900,242.199,...,11140.107,6507.286,260.964,-1407.357,19094.143,1962.000,83.870,6.079,Not Available,2126.000
2,1973-03-01,51188.000,-3467,1189.42,45403,129.763,Not Available,129.938,400.161,268.810,...,11006.419,6610.161,224.194,672.806,17216.226,1907.000,91.581,4.021,Not Available,2015.000
3,1973-04-01,47580.000,-5117,1218.52,43326.5,125.462,Not Available,125.636,380.470,253.185,...,11041.500,5593.367,275.567,871.267,15920.533,1814.000,88.407,8.017,Not Available,1835.000
4,1973-05-01,52061.000,-5221,4230.62,43999.8,129.624,Not Available,129.834,392.141,260.770,...,11001.645,5840.935,237.387,658.032,16625.806,1898.000,85.844,8.741,Not Available,1729.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,2020-03-01,46060.926,-6452.71,4765.74,32736.5,189.162,183.663,410.886,995.023,202.739,...,17989.939,8344.839,9621.232,1333.636,18283.773,3156.571,217.087,497.399,49.134,2709.209
567,2020-04-01,38999.501,-5115.03,6838.55,26686.8,182.014,112.893,330.230,919.439,189.099,...,16944.243,7235.567,8451.540,2653.558,14690.988,2992.824,193.401,420.731,-306.21,2243.949
568,2020-05-01,36934.071,-4221.94,2648.24,29787.3,190.617,136.585,363.013,1040.212,268.273,...,14763.656,7756.871,6817.574,1242.020,16103.228,2925.016,189.403,395.307,-448.006,2068.441
569,2020-06-01,39258.833,-4295.05,-5671.24,39902.4,179.179,164.111,375.833,1060.066,260.567,...,15643.708,8367.233,7692.178,1168.138,17435.204,2872.114,185.143,338.444,-357.949,2135.630
570,2020-07-01,43086.574,-4885.63,-13484.3,53263.5,185.801,180.789,401.080,1003.547,236.338,...,16352.690,7845.581,8411.704,-56.598,18322.588,3021.945,212.953,335.373,-161.372,2494.742

In [63]:
# Dropping year 2020
drop_half = final_combine.drop(final_combine.index[564:571])
drop_half

,Month,Coal Production (Thousand Short Tons),Coal Net Imports (Thousand Short Tons),Coal Stock Change (Thousand Short Tons),Coal Consumption (Thousand Short Tons),Wood Energy Production (Trillion Btu),Biofuels Production (Trillion Btu),Total Biomass Energy Production (Trillion Btu),Total Renewable Energy Production (Trillion Btu),Hydroelectric Power Consumption (Trillion Btu),...,Total Petroleum Field Production (Thousand Barrels per Day),Petroleum Imports (Thousand Barrels per Day),Petroleum Exports (Thousand Barrels per Day),Petroleum Stock Change (Thousand Barrels per Day),Petroleum Products Supplied (Thousand Barrels per Day),Natural Gas Marketed Production (Wet) (Billion Cubic Feet),Natural Gas Imports (Billion Cubic Feet),Natural Gas Exports (Billion Cubic Feet),Natural Gas Net Storage Withdrawals (Billion Cubic Feet),Natural Gas Consumption (Billion Cubic Feet)
0,1973-01-01,49901.000,-2993,7744.46,50578.6,129.630,Not Available,129.787,403.981,272.703,...,10855.968,5857.097,210.613,-1718.323,18712.645,1948.000,92.694,5.808,Not Available,2348.000
1,1973-02-01,46461.000,-2672,-1997.88,45564.8,117.194,Not Available,117.338,360.900,242.199,...,11140.107,6507.286,260.964,-1407.357,19094.143,1962.000,83.870,6.079,Not Available,2126.000
2,1973-03-01,51188.000,-3467,1189.42,45403,129.763,Not Available,129.938,400.161,268.810,...,11006.419,6610.161,224.194,672.806,17216.226,1907.000,91.581,4.021,Not Available,2015.000
3,1973-04-01,47580.000,-5117,1218.52,43326.5,125.462,Not Available,125.636,380.470,253.185,...,11041.500,5593.367,275.567,871.267,15920.533,1814.000,88.407,8.017,Not Available,1835.000
4,1973-05-01,52061.000,-5221,4230.62,43999.8,129.624,Not Available,129.834,392.141,260.770,...,11001.645,5840.935,237.387,658.032,16625.806,1898.000,85.844,8.741,Not Available,1729.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,2019-08-01,63794.620,-7229.78,954.756,56464,210.748,199.004,445.598,947.910,191.559,...,17190.640,9386.613,8437.641,-270.645,21157.914,3159.401,220.076,384.983,-303.348,2440.706
560,2019-09-01,58597.420,-7090.8,1792.12,51325.7,196.224,182.097,411.846,897.109,148.611,...,17484.687,8711.767,8671.817,-76.595,20248.481,3053.609,208.286,394.511,-439.79,2217.254
561,2019-10-01,57674.057,-5847.62,10053.3,41491.7,195.969,191.976,424.908,933.440,148.320,...,17694.810,8599.194,9039.354,-531.711,20713.986,3199.983,210.537,425.775,-363.774,2327.959
562,2019-11-01,54392.702,-7116.28,5014.33,45853.6,196.174,191.984,424.845,924.473,186.814,...,17854.280,8103.200,8741.263,-283.900,20736.154,3119.588,223.765,441.362,159.096,2778.553
563,2019-12-01,53183.707,-5975.96,6057.7,44529.9,205.881,203.464,447.507,968.694,202.164,...,17793.613,9159.452,9330.737,-43.810,20442.870,3232.454,256.053,481.006,433.402,3148.053

In [64]:
# Removing data before 1980
drop_final = drop_half.drop(drop_half.index[0:84])
drop_final

,Month,Coal Production (Thousand Short Tons),Coal Net Imports (Thousand Short Tons),Coal Stock Change (Thousand Short Tons),Coal Consumption (Thousand Short Tons),Wood Energy Production (Trillion Btu),Biofuels Production (Trillion Btu),Total Biomass Energy Production (Trillion Btu),Total Renewable Energy Production (Trillion Btu),Hydroelectric Power Consumption (Trillion Btu),...,Total Petroleum Field Production (Thousand Barrels per Day),Petroleum Imports (Thousand Barrels per Day),Petroleum Exports (Thousand Barrels per Day),Petroleum Stock Change (Thousand Barrels per Day),Petroleum Products Supplied (Thousand Barrels per Day),Natural Gas Marketed Production (Wet) (Billion Cubic Feet),Natural Gas Imports (Billion Cubic Feet),Natural Gas Exports (Billion Cubic Feet),Natural Gas Net Storage Withdrawals (Billion Cubic Feet),Natural Gas Consumption (Billion Cubic Feet)
84,1980-01-01,69594.000,-4339.82,-973.956,63518.5,209.613,Not Available,209.829,478.943,265.618,...,10323.806,8598.032,549.710,324.419,18851.484,1821.000,118.006,6.444,416,2237.743
85,1980-02-01,65546.000,-3847.28,-1080.77,59678.4,196.117,Not Available,196.310,424.298,224.631,...,10360.448,7944.690,558.276,-270.655,18817.207,1709.000,108.192,4.857,440,2146.771
86,1980-03-01,70953.000,-5540.21,1403.52,58851.9,209.598,Not Available,209.727,469.134,255.676,...,10266.194,7452.387,572.903,145.871,17376.903,1830.000,108.648,4.799,231,2053.945
87,1980-04-01,69658.000,-7499.26,8931.61,52635.3,202.768,Not Available,202.894,477.356,270.552,...,10314.833,7105.900,433.733,640.967,16784.467,1670.000,77.257,3.245,-104,1534.606
88,1980-05-01,71043.000,-8389.46,8767.2,52833.6,209.394,Not Available,209.548,517.456,303.305,...,10250.258,6578.710,591.258,636.871,16237.742,1695.000,70.207,3.144,-297,1356.886
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
559,2019-08-01,63794.620,-7229.78,954.756,56464,210.748,199.004,445.598,947.910,191.559,...,17190.640,9386.613,8437.641,-270.645,21157.914,3159.401,220.076,384.983,-303.348,2440.706
560,2019-09-01,58597.420,-7090.8,1792.12,51325.7,196.224,182.097,411.846,897.109,148.611,...,17484.687,8711.767,8671.817,-76.595,20248.481,3053.609,208.286,394.511,-439.79,2217.254
561,2019-10-01,57674.057,-5847.62,10053.3,41491.7,195.969,191.976,424.908,933.440,148.320,...,17694.810,8599.194,9039.354,-531.711,20713.986,3199.983,210.537,425.775,-363.774,2327.959
562,2019-11-01,54392.702,-7116.28,5014.33,45853.6,196.174,191.984,424.845,924.473,186.814,...,17854.280,8103.200,8741.263,-283.900,20736.154,3119.588,223.765,441.362,159.096,2778.553
563,2019-12-01,53183.707,-5975.96,6057.7,44529.9,205.881,203.464,447.507,968.694,202.164,...,17793.613,9159.452,9330.737,-43.810,20442.870,3232.454,256.053,481.006,433.402,3148.053